### PR TITLE
Workarounds according fmalk/codeigniter-phpunit#21:

### PR DESCRIPTION
**Pull request by feryardiant**
- [x] Add CI_VERSION enviroment on .travis.yml
- [x] mv phpunit.xml application/test/phpunit.xml
- [x] Add is_cli() function overwrite
- [x] mv system/core system/core2 #for CI 2.x
- [x] Add system/core3 #for CI 3.x

### CODE REVIEW

**Comment by fmalk** [comment]
Great work @feryardiant 
We should put this on a 3.x branch of the project. But if I'm going to do this, I think we must keep `core` folder with its original name so it won't mess with "core2"  projects

**Comment by fmalk** [comment]
I've merged it under a new CI3 branch. We should keep both versions separated.

**Comment by feryardiant** [comment]
If you want to use `display_override` hooks, you doesn't need to overwrite `system/core` at all (for both CI 2.x & 3.x)

**Comment by feryardiant** [comment]
and sorry if I'm not updating the `README`, My english is too bad to give explanation :sweat_smile:

**Pull request closed without merging**
